name: Auto Approve PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  auto-approve:
    if: github.event.repository.name == 'aghast'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
